<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Cleaning Paper — Full Facility | {{ now()->format('d M Y') }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #000; background: #fff; padding: 30px; }
        .top-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .print-btns button { padding: 10px 24px; font-size: 13px; font-weight: bold; cursor: pointer; border: none; margin-left: 8px; }
        .btn-print { background: #000; color: #fff; }
        .btn-close { background: #eee; color: #333; }
        .header { text-align: center; border-bottom: 3px double #000; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { font-size: 24px; font-weight: 900; text-transform: uppercase; letter-spacing: 1px; }
        .header .subtitle { font-size: 13px; font-weight: bold; color: #444; margin-top: 4px; }
        .header .doc-type { display: inline-block; margin-top: 8px; padding: 3px 20px; border: 2.5px solid #000; font-size: 11px; font-weight: 900; letter-spacing: 3px; text-transform: uppercase; }
        .meta { display: flex; justify-content: space-between; font-size: 13px; font-weight: bold; padding: 10px 0; border-bottom: 1px solid #ccc; margin-bottom: 20px; }
        .floor-section { margin-bottom: 28px; page-break-inside: avoid; }
        .floor-header { background: #000; color: #fff; padding: 8px 14px; font-size: 13px; font-weight: 900; text-transform: uppercase; letter-spacing: 2px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1.5px solid #000; padding: 9px 12px; font-size: 13px; text-align: left; }
        th { background: #f0f0f0; font-weight: 900; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; }
        .status-badge { display: inline-block; padding: 2px 10px; border: 1.5px solid currentColor; font-size: 11px; font-weight: bold; text-transform: uppercase; }
        .status-pending     { color: #b45309; }
        .status-in_progress { color: #1d4ed8; }
        .summary-box { border: 2px solid #000; padding: 14px 20px; margin-top: 20px; display: flex; justify-content: space-between; font-size: 13px; font-weight: bold; }
        .no-data-box { border: 3px dashed #ccc; padding: 50px 20px; text-align: center; color: #999; font-size: 16px; margin: 30px 0; }
        .footer { margin-top: 50px; display: flex; justify-content: space-between; gap: 20px; }
        .sig-box { flex: 1; text-align: center; }
        .sig-line { border-top: 1.5px solid #000; margin-top: 45px; padding-top: 6px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
        @media print {
            .no-print { display: none !important; }
            body { padding: 10px; }
            .floor-section { page-break-inside: avoid; }
        }
    </style>
</head>
<body>

    <div class="top-bar no-print">
        <div style="font-size:13px; color:#555;">
            <strong>Live Document.</strong> Shows only <u>pending / in-progress</u> tasks. Generated: <strong>{{ now()->format('d M Y H:i:s') }}</strong>
        </div>
        <div class="print-btns">
            <button class="btn-print" onclick="window.print()">🖨 Print Cleaning Paper</button>
            <button class="btn-close" onclick="window.close()">✕ Close</button>
        </div>
    </div>

    <div class="header">
        <h1>Hospital Washroom Management System</h1>
        <div class="subtitle">Command Center — Full Facility Cleaning Audit</div>
        <div class="doc-type">Cleaning Paper — Admin Facility Manifest</div>
    </div>

    <div class="meta">
        <div>
            <div>Generated By: <strong>{{ $admin->name }}</strong> (COMMAND)</div>
            <div>Scope: <strong>Full Facility — All Floors — Pending Tasks Only</strong></div>
        </div>
        <div style="text-align:right;">
            <div>Date &amp; Time: <strong>{{ now()->format('d M Y — H:i:s') }}</strong></div>
            <div>Reference: <strong>#WMS-ADM-{{ now()->format('Ymd-Hi') }}</strong></div>
        </div>
    </div>

    @php
        $grandPending = $floors->sum(fn($f) => $f->tasks->whereIn('status', ['pending', 'in_progress'])->count());
    @endphp

    @if($grandPending === 0)
        <div class="no-data-box">
            <strong>NO PENDING CLEANING TASKS FACILITY-WIDE</strong><br><br>
            All tasks are completed, or no tasks have been allocated yet.<br>
            <span style="font-size:13px;">Assign tasks from the Command Center dashboard to populate this paper.</span>
        </div>
    @else
        @foreach($floors as $floor)
            @php
                $pendingTasks = $floor->tasks->whereIn('status', ['pending', 'in_progress']);
            @endphp
            @if($pendingTasks->count() > 0)
                <div class="floor-section">
                    <div class="floor-header">
                        {{ $floor->name }} — {{ $pendingTasks->count() }} Pending Unit(s)
                    </div>
                    <table>
                        <thead>
                            <tr>
                                <th style="width:45px;">S.No</th>
                                <th style="width:130px;">Room / Unit No.</th>
                                <th>Unit Type</th>
                                <th>Operative (Assignee)</th>
                                <th>Task Description</th>
                                <th style="width:130px;">Status</th>
                                <th style="width:150px;">Audit Check</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $rowNum = 1; @endphp
                            @foreach($pendingTasks as $task)
                                @php
                                    $roomNo   = $task->room->room_number ?? $task->washroom->room_number ?? '—';
                                    $unitType = ($task->room_id && $task->room)
                                        ? ucfirst($task->room->type ?? 'Standard').' Room'
                                        : 'Public Washroom';
                                @endphp
                                <tr>
                                    <td>{{ $rowNum++ }}</td>
                                    <td><strong>{{ $roomNo }}</strong></td>
                                    <td>{{ $unitType }}</td>
                                    <td>{{ $task->assignee->name ?? 'Unassigned' }}</td>
                                    <td>{{ $task->description ?? 'Standard Cleaning Protocol' }}</td>
                                    <td>
                                        <span class="status-badge status-{{ $task->status }}">
                                            {{ strtoupper(str_replace('_', ' ', $task->status)) }}
                                        </span>
                                    </td>
                                    <td style="font-size:12px;">[ ] OK &nbsp; [ ] Failed: _____</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        @endforeach

        <div class="summary-box">
            <div>Total Pending Units: <strong>{{ $grandPending }}</strong></div>
            <div>Completed tasks are excluded from this paper.</div>
            <div>Ref: #WMS-ADM-{{ now()->format('Ymd') }}</div>
        </div>
    @endif

    <div class="footer">
        <div class="sig-box"><div class="sig-line">Facility Manager</div></div>
        <div class="sig-box"><div class="sig-line">Protocol Supervisor</div></div>
        <div class="sig-box"><div class="sig-line">Command Center Official</div></div>
    </div>

</body>
</html>

