<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Complaints Report | WMS | {{ now()->format('d M Y') }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #000; background: #fff; padding: 30px; }
        .top-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .print-btns button { padding: 10px 24px; font-size: 13px; font-weight: bold; cursor: pointer; border: none; margin-left: 8px; }
        .btn-print { background: #000; color: #fff; }
        .btn-close { background: #eee; color: #333; }

        .header { text-align: center; border-bottom: 3px double #000; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { font-size: 22px; font-weight: 900; text-transform: uppercase; letter-spacing: 1px; }
        .header .subtitle { font-size: 13px; color: #555; margin-top: 5px; }
        .header .doc-type { display: inline-block; margin-top: 8px; padding: 4px 20px; border: 2.5px solid #000; font-size: 11px; font-weight: 900; letter-spacing: 3px; text-transform: uppercase; }

        .meta { display: flex; justify-content: space-between; font-size: 13px; font-weight: bold; padding: 10px 0; border-bottom: 1px solid #ccc; margin-bottom: 20px; }

        
        .summary-strip { display: flex; gap: 0; border: 2px solid #000; margin-bottom: 25px; }
        .summary-strip .item { flex: 1; padding: 12px; text-align: center; border-right: 1.5px solid #000; }
        .summary-strip .item:last-child { border-right: none; }
        .summary-strip .num { font-size: 22px; font-weight: 900; }
        .summary-strip .lbl { font-size: 10px; font-weight: 900; text-transform: uppercase; color: #666; }

        
        .complaint-block { border: 1.5px solid #000; margin-bottom: 20px; page-break-inside: avoid; }
        .complaint-header { background: #000; color: #fff; padding: 8px 14px; display: flex; justify-content: space-between; align-items: center; }
        .complaint-header .id { font-size: 11px; font-weight: 900; letter-spacing: 1px; }
        .complaint-header .stamp { font-size: 11px; font-weight: 900; padding: 2px 10px; border: 1.5px solid #fff; text-transform: uppercase; }
        .complaint-body { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 0; }
        .complaint-body .cell { padding: 10px 14px; border-right: 1px solid #ccc; border-bottom: 1px solid #ccc; }
        .complaint-body .cell:nth-child(3n) { border-right: none; }
        .complaint-body .cell .lbl { font-size: 10px; font-weight: 900; text-transform: uppercase; color: #888; margin-bottom: 4px; }
        .complaint-body .cell .val { font-size: 13px; font-weight: bold; }
        .complaint-desc { padding: 10px 14px; border-top: 1px solid #ddd; font-size: 13px; }
        .complaint-desc .lbl { font-size: 10px; font-weight: 900; text-transform: uppercase; color: #888; margin-bottom: 4px; }

        
        .stamp-pending     { border-color: #fbbf24 !important; color: #fbbf24; }
        .stamp-in_progress { border-color: #93c5fd !important; color: #93c5fd; }
        .stamp-resolved    { border-color: #6ee7b7 !important; color: #6ee7b7; }

        .no-data-box { border: 3px dashed #ccc; padding: 50px 20px; text-align: center; color: #999; font-size: 16px; margin: 30px 0; }

        .footer { margin-top: 50px; display: flex; justify-content: space-between; gap: 20px; }
        .sig-box { flex: 1; text-align: center; }
        .sig-line { border-top: 1.5px solid #000; margin-top: 45px; padding-top: 6px; font-size: 12px; font-weight: bold; text-transform: uppercase; }

        @media print {
            .no-print { display: none !important; }
            body { padding: 10px; }
            .complaint-block { page-break-inside: avoid; }
        }
    </style>
</head>
<body>

    <div class="top-bar no-print">
        <div style="font-size:13px; color:#555;">
            <strong>Live Complaint Report.</strong> All active complaints pulled from database. Generated: <strong>{{ now()->format('d M Y H:i:s') }}</strong>
        </div>
        <div class="print-btns">
            <button class="btn-print" onclick="window.print()">🖨 Print All Complaints</button>
            <button class="btn-close" onclick="window.close()">✕ Close</button>
        </div>
    </div>

    <div class="header">
        <h1>Hospital Washroom Management System</h1>
        <div class="subtitle">Support & Incident Resolution Division</div>
        <div class="doc-type">Complaint Paper — All Incidents Report</div>
    </div>

    <div class="meta">
        <div>
            <div>Generated By: <strong>{{ $generatedBy ?? 'System' }}</strong></div>
            <div>Report Scope: <strong>All Active Complaints</strong></div>
        </div>
        <div style="text-align:right;">
            <div>Date &amp; Time: <strong>{{ now()->format('d M Y — H:i:s') }}</strong></div>
            <div>Reference: <strong>#WMS-CPT-{{ now()->format('Ymd-Hi') }}</strong></div>
        </div>
    </div>

    @php
        $total      = $complaints->count();
        $pending    = $complaints->where('status', 'pending')->count();
        $inProgress = $complaints->where('status', 'in_progress')->count();
        $resolved   = $complaints->where('status', 'resolved')->count();
    @endphp

    
    <div class="summary-strip">
        <div class="item"><div class="num">{{ $total }}</div><div class="lbl">Total</div></div>
        <div class="item"><div class="num">{{ $pending }}</div><div class="lbl">Pending</div></div>
        <div class="item"><div class="num">{{ $inProgress }}</div><div class="lbl">In Progress</div></div>
        <div class="item"><div class="num">{{ $resolved }}</div><div class="lbl">Resolved</div></div>
    </div>

    @if($total === 0)
        <div class="no-data-box">
            <strong>NO PENDING/IN-PROGRESS COMPLAINTS</strong><br><br>
            All complaints are completed, or no active incidents have been detected.
        </div>
    @else
        @foreach($complaints as $c)
            @php
                $location = '';
                if ($c->room) {
                    $location = 'Room ' . $c->room->room_number . ' (' . strtoupper($c->room->type ?? 'ROOM') . ')';
                } elseif ($c->washroom) {
                    $location = ($c->washroom->room_number ?? $c->washroom->name) . ' (PUBLIC)';
                } else {
                    $location = 'General Floor Area';
                }
            @endphp
            <div class="complaint-block">
                <div class="complaint-header">
                    <div class="id">Incident #{{ strtoupper(substr((string)($c->_id ?? $c->id), -8)) }}</div>
                    <div class="stamp stamp-{{ $c->status }}">{{ strtoupper(str_replace('_', ' ', $c->status)) }}</div>
                </div>
                <div class="complaint-body">
                    <div class="cell">
                        <div class="lbl">Room / Unit</div>
                        <div class="val">{{ $location }}</div>
                    </div>
                    <div class="cell">
                        <div class="lbl">Floor</div>
                        <div class="val">{{ $c->floor->name ?? 'N/A' }}</div>
                    </div>
                    <div class="cell">
                        <div class="lbl">Issue Type</div>
                        <div class="val">{{ $c->complaint_type ?? 'N/A' }}</div>
                    </div>
                    <div class="cell">
                        <div class="lbl">Reported By</div>
                        <div class="val">{{ $c->user->name ?? 'Anonymous' }}</div>
                    </div>
                    <div class="cell">
                        <div class="lbl">Reported Date</div>
                        <div class="val">{{ $c->created_at->format('d M Y') }}<br><span style="font-size:11px;font-weight:normal;">{{ $c->created_at->format('H:i:s') }}</span></div>
                    </div>
                    <div class="cell">
                        <div class="lbl">Resolved At</div>
                        <div class="val">{{ $c->resolved_at ? $c->resolved_at->format('d M Y') : '—' }}</div>
                    </div>
                </div>
                @if($c->description || $c->admin_notes)
                    <div class="complaint-desc">
                        @if($c->description)
                            <div class="lbl">Description</div>
                            <div>{{ $c->description }}</div>
                        @endif
                        @if($c->admin_notes)
                            <div class="lbl" style="margin-top:6px;">Handler Notes</div>
                            <div>{{ $c->admin_notes }}</div>
                        @endif
                    </div>
                @endif
            </div>
        @endforeach
    @endif

    <div class="footer">
        <div class="sig-box"><div class="sig-line">Maintenance Supervisor</div></div>
        <div class="sig-box"><div class="sig-line">Facility Manager</div></div>
        <div class="sig-box"><div class="sig-line">Audit Representative</div></div>
    </div>

</body>
</html>

